[package]
name = "crane2"
version = "0.1.0"
edition = "2021"

[lib]
name = "crane"
path = "src/lib.rs"

[dependencies]
ariadne = { git = "https://github.com/zesterer/ariadne", version = "0.3.0", features = ["auto-color"] }
chumsky = { version = "1.0.0-alpha.6", features = ["pratt"] }
